devPort: 14300
# ServerProperties
server:
  port: 10220
  context-path: /shop/rs/local/14300               # todo 其它环境修改该行
  error.include-stacktrace: on_trace_param

# SecurityProperties
security:
  basic.enabled: false



# QhAgencyProperties
net.kingsilk.qh.agency:
  # http代理设置
  http:
    proxy:
      enabled:      false
  qhOAuth:
    wap:
      url:                      'https://kingsilk.net/oauth/local/14300/rs'           # todo 其它环境修改该行
  qhPay:
    wap:
      url:                      'https://pay.kingsilk.net/qh/pay/local/14300/rs'       # todo 其它环境修改该行
  qhAgency:
    wap:
      url:                      'https://agency.kingsilk.net/local/14300/rs/api'       # TODO 其它环境修改该行
  agencyUt:
    basePath :                  'https://kingsilk.net/agency/rs/local/${devPort}/api'

# MongoProperties
spring.data.mongodb:
  host: '192.168.0.12'
  port: 27017
  database: 'shop'
  username: 'shop'
  password: 'shop'

ut:
    basePath : 'https://agency.kingsilk.net/local/${devPort}/rs/api'

