devPort: 16000
# ServerProperties
server:
  port: 10200
  context-path: /admin/local/${devPort}/rs                           # todo 其它环境修改该行
  error.include-stacktrace: on_trace_param

# SecurityProperties
security:
  basic.enabled: false



# QhAgencyProperties
net.kingsilk.qh.platform:
  # http代理设置
  http:
    proxy:
      enabled:      false
  qhOAuth:
    wap:
      url:                      'https://kingsilk.net/oauth/local/${devPort}/rs'           # todo 其它环境修改该行
  qhPay:
    wap:
      url:                      'https://pay.kingsilk.net/qh/pay/local/${devPort}/rs'       # todo 其它环境修改该行

# MongoProperties
spring.data.mongodb:
  host: '192.168.0.12'
  port: 27017
  database: 'qh-platform'
  username: 'qh-platform'
  password: 'qh-platform'


ut:
    basePath : https://kingsilk.net/oauth2/rs/local/${devPort}/api

agencyUt:
    basePath : https://kingsilk.net/agency/rs/local/${devPort}/api