# MongoProperties
spring.data.mongodb:
    host: '192.168.0.12'
    port: 27017
    database: 'qh-platform'
    username: 'qh-platform'
    password: 'qh-platform'

#
#  host: 'prod14.kingsilk.net'
#  port: 27017
#  database: 'qh-platform'
#  username: 'qh-platform'
#  password: '{qhAgency2017]'