devPort: 14100

# ServerProperties
server:
  context-path: /oauth2/rs/local/${devPort}

# LOGGING
logging:
  level:
    org.springframework.web:                                                      INFO
    org.springframework.security:                                                 INFO
    org.springframework.boot.actuate.audit.listener.AuditListener:                DEBUG
    org.springframework.boot.web.support.ErrorPageFilter:                         DEBUG
    org.springframework.web.servlet.view.ContentNegotiatingViewResolver:          DEBUG
    org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping:  DEBUG
    org.apache.http.wire:                                                         DEBUG
    net.kingsilk:                                                                 DEBUG

# MongoProperties
spring.data.mongodb:
  host: 'localhost'
  port: 27017
  database: 'qhOauth'
  username: 'qhOauth'
  password: 'qhOauth'

# QhOAuthProperties
net.kingsilk.qh.oauth:
  # http代理设置
  http:
    proxy:
      enabled:      false

  qhOAuth:
    wap:
      url:          https://kingsilk.net/local/${devPort}/rs
      wx:
        wx:
        # 小皇叔 微信公众号
        appId: wxbba6def439fc0bd0
        appSecret: 2b93ea75514ab12d07085b249e167dc3
#        # 钱皇内部测试号
#        appId:      wxf9f2b8b1a506c068
#        appSecret:  9c2fe3b32ceda561a63f267eb116473a
  qhCommon:
    admin:
      url:          http://localhost:10100/admin/local/${devPort}/rs
  wx4j:
    broker:
      apiBaseUri:       https://kingsilk.net/wx/local/14100/rs/api
